version: '3.3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'weddings'
      # Create a Database User so I don't have to use root
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    # Where data will be persisted
    volumes:
      - weddings-db:/var/lib/mysql
# Names the volume
volumes:
  weddings-db: